services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.5.6  
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 512M

  portainer:
    image: portainer/portainer-ce:2.11.1  
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  grafana-storage:
  portainer_data: